name: Build and Deploy to Netlify and Vercel
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      deploy-netlify:
        type: boolean
        description: Enable Netlify deployment
        default: true
      deploy-vercel:
        type: boolean
        description: Enable Vercel deployment
        default: true

jobs:
  test:
    uses: ./.github/workflows/tests.yml
  build:
    needs: test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        timeout-minutes: 5

      - name: Build app
        run: npm run build
        timeout-minutes: 5

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        timeout-minutes: 1
        if: ${{ inputs.deploy-netlify }}
        with:
          publish-dir: './dist'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ vars.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ vars.NETLIFY_SITE_ID }}

      - name: Install Vercel CLI
        if: ${{ inputs.deploy-vercel }}
        run: npm install --global vercel@canary

      - name: Pull Vercel Environment Information
        if: ${{ inputs.deploy-vercel }}
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts for Vercel
        if: ${{ inputs.deploy-vercel }}
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        if: ${{ inputs.deploy-vercel }}
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}