name: Build and Deploy to Netlify and Vercel

on:
  push:
    branches:
      - master

jobs:
  test:
    uses: ./.github/workflows/tests.yml
  deploy-netlify:
    uses: ./.github/workflows/deploy-netlify.yml
    secrets:
      NETLIFY_AUTH_TOKEN: ${{ vars.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ vars.NETLIFY_SITE_ID }}

  deploy-vercel:
    needs: deploy-netlify
    uses: ./.github/workflows/deploy-vercel.yml
    secrets: inherit