name: Build and Deploy to Netlify
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      deploy-netlify:
        type: boolean
        description: Enable Netlify deployment
        default: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: ./.github/workflows/test.yml
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        timeout-minutes: 5

      - name: Build app
        run: npm run build
        timeout-minutes: 5

      - name: Deploy to Netlify
        # if: |
        #   github.event_name == 'push' ||
        #   (github.event_name == 'workflow_dispatch' && inputs.deploy-netlify == true)
        uses: nwtgck/actions-netlify@v3.0
        timeout-minutes: 1
        if: ${{ inputs.deploy-netlify }}
        with:
          publish-dir: './dist'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ vars.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ vars.NETLIFY_SITE_ID }}